module.exports = {
  port: process.env.PORT || 8080,
  baseUrl: process.env.BASE_URL || `http://localhost:${process.env.PORT || 8080}`,
  supabaseUrl: process.env.SUPABASE_URL || '',
  supabaseKey: process.env.SUPABASE_KEY || '',
  apolloApiKey: process.env.APOLLO_API_KEY || '',
  apolloBaseUrl: process.env.APOLLO_BASE_URL || '',
  umamiToken: process.env.UMAMI_TOKEN || '',
  umamiSiteId: process.env.UMAMI_SITE_ID || '',
  sentryDsn: process.env.SENTRY_DSN || '',
  sentryAuthToken: process.env.SENTRY_AUTH_TOKEN || '',
  twitterBearer: process.env.TWITTER_BEARER_TOKEN || '',
  trustmrrKey: process.env.TRUSTMRR_API_KEY || '',
  trustmrrBase: process.env.TRUSTMRR_BASE_URL || '',
  gumroadClientId: process.env.GUMROAD_CLIENT_ID || '',
  gumroadClientSecret: process.env.GUMROAD_CLIENT_SECRET || '',
  betalistRss: process.env.BETALIST_RSS_URL || '',
  solidgigsEmail: process.env.SOLIDGIGS_INBOUND_EMAIL || '',
  contraEmail: process.env.CONTRA_INBOUND_EMAIL || '',
  agentscopeUrl: process.env.AGENTSCOPE_API_URL || '',
  agentscopeKey: process.env.AGENTSCOPE_API_KEY || '',
  verdentKey: process.env.VERDENT_API_KEY || '',
  groSecret: process.env.GRO_WEBHOOK_SECRET || '',
  headaiKey: process.env.HEADAI_API_KEY || '',
  webrobotsKey: process.env.WEBROBOTS_API_KEY || '',
  startupsRipRss: process.env.STARTUPSRIP_RSS || '',
  foundersDbKey: process.env.FOUNDERSDB_API_KEY || '',
  paperclipKey: process.env.PAPERCLIP_API_KEY || '',
};
