const express = require('express');
const router = express.Router();
const db = require('../db');
const aiService = require('../services/aiService');
const sentryService = require('../services/sentryService');
const umamiService = require('../services/umamiService');
const trustmrrService = require('../services/trustmrrService');
const { asyncHandler, ok } = require('../utils/helpers');

async function buildMissions() {
  const [leads, health] = await Promise.all([
    db.list('leads', { orderBy: { column: 'score', ascending: false }, limit: 10 }),
    sentryService.getIssues(),
  ]);

  if (health.critical > 0) {
    return [{ text: 'Site has a critical error affecting the contact form — fix before anything else today.', priority: 1 }];
  }

  // Locked leads are already being actively worked — don't re-suggest them as missions.
  const hotLeads = leads.filter((l) => (l.score || 0) >= 8 && !l.locked);
  const fallback = [
    hotLeads[0] && { text: `Follow up with ${hotLeads[0].name || hotLeads[0].company} — score ${hotLeads[0].score}/10, highest-intent lead right now.`, priority: 1 },
    { text: 'Review yesterday\'s Apollo sequence replies and send follow-ups.', priority: 2 },
    { text: 'Post today\'s Twitter thread and reply to 3 top tweets in your niche.', priority: 3 },
  ].filter(Boolean);

  const text = await aiService.safeComplete(
    {
      system:
        'You are the War Room briefing generator for a solo backend engineering founder. Given hot leads and pipeline state, ' +
        'output exactly 3 concrete actions ranked by probability of landing a client this week. Return JSON: {"missions": ["...", "...", "..."]}.',
      prompt: JSON.stringify({ hotLeads: hotLeads.slice(0, 5) }),
      json: true,
      maxTokens: 300,
    },
    null
  );
  if (!text) return fallback;
  try {
    const parsed = JSON.parse(text);
    return (parsed.missions || []).map((m, i) => ({ text: m, priority: i + 1 }));
  } catch {
    return fallback;
  }
}

// GET /api/warroom/missions — cached per-day, regenerated by the 7am cron (or on first request of the day)
router.get('/missions', asyncHandler(async (req, res) => {
  const today = new Date().toISOString().slice(0, 10);
  const settings = await db.getSettings();
  const key = `warroom_missions_${today}`;
  if (settings[key]) return ok(res, settings[key]);

  const missions = await buildMissions();
  await db.updateSettings({ [key]: missions });
  ok(res, missions);
}));

// GET /api/warroom/feed — aggregated live alerts (new leads, replies, traffic spikes, errors)
router.get('/feed', asyncHandler(async (req, res) => {
  const [leads, health, active] = await Promise.all([
    db.list('leads', { orderBy: { column: 'created_at', ascending: false }, limit: 20 }),
    sentryService.getIssues(),
    umamiService.getActiveVisitors(),
  ]);

  const feed = [
    ...leads.slice(0, 10).map((l) => ({
      type: 'lead',
      text: `New lead: ${l.name || l.company || 'Unknown'} (${l.source}, score ${l.score}/10)`,
      timestamp: l.created_at,
    })),
    ...(health.critical > 0
      ? [{ type: 'alert', text: `${health.critical} critical site error(s) — check Analytics Tower`, timestamp: new Date().toISOString() }]
      : []),
    ...(active.visitors >= 20
      ? [{ type: 'traffic', text: `Traffic spike: ${active.visitors} live visitors right now`, timestamp: new Date().toISOString() }]
      : []),
  ].sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));

  ok(res, feed);
}));

// GET /api/warroom/summary — pipeline + revenue meter for the home screen at a glance
router.get('/summary', asyncHandler(async (req, res) => {
  const [leads, mrr] = await Promise.all([db.list('leads'), trustmrrService.getMrr()]);
  const stages = ['new', 'contacted', 'replied', 'call_booked', 'proposal_sent', 'closed_won'];
  const pipeline = stages.reduce((acc, s) => {
    acc[s] = leads.filter((l) => l.status === s).length;
    return acc;
  }, {});
  ok(res, { pipeline, mrr: mrr.mrr, arr: mrr.arr });
}));

module.exports = router;
module.exports.buildMissions = buildMissions;
